apiVersion: v1
kind: Namespace
metadata:
  name: spark-operator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-operator
  namespace: spark-operator
spec:
  replicas: 1
  selector:
    matchLabels: {app: spark-operator}
  template:
    metadata:
      labels: {app: spark-operator}
    spec:
      serviceAccountName: spark-operator-svc
      containers:
        - name: spark-operator
        image: gcr.io/spark-operator/spark-operator:v1beta2-1.3.8-3.5.0
        args:
          - --enable-webhook=true
          - --install-crds=true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark-operator-svc
  namespace: spark-operator